backend:
  name: git-gateway
  branch: main # если у тебя репозиторий на ветке master — поменяй здесь

media_folder: "public/assets/images/posts"   # куда сохранять картинки внутри проекта
public_folder: "/assets/images/posts"        # откуда их забирать на сайте

collections:
  - name: "posts"
    label: "Пости"
    folder: "public/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      # - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
      - { label: "Зображення", name: "image", widget: "image" }



# backend:
#   name: git-gateway
#   branch: main   # ветка в GitHub

# media_folder: "public/uploads"   # папка для загрузки картинок
# public_folder: "/uploads"

# collections:
#   - name: "posts"
#     label: "Посты"
#     folder: "content/posts"
#     create: true
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#     fields:
#       - { name: "title", label: "Заголовок", widget: "string" }
#       - { name: "image", label: "Картинка", widget: "image" }
#       - { name: "body", label: "Текст", widget: "markdown" }

