backend:
  name: git-gateway
  branch: main


media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Пости"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"

      - label: "Зображення"
        name: "image"
        widget: "image"
        choose_url: false
        # default: "/assets/images/default.jpg" # необязательно, можно убратьcd 

      - label: "Текст"
        name: "body"
        widget: "markdown"